CREATE TABLE MANAGERS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE CUSTOMERS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    MANAGERID INT,
    FOREIGN KEY (MANAGERID) REFERENCES MANAGERS(ID)
);

CREATE TABLE ORDERS (
    ID INT PRIMARY KEY,
    DATE DATE,
    AMOUNT DECIMAL(10, 2),
    CUSTOMERID INT,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(ID)
);

