SELECT 
    C.NAME AS CustomerName, 
    M.NAME AS ManagerName,
    COUNT(*) AS TotalOrders,
    SUM(O.AMOUNT) AS TotalAmount
FROM 
    CUSTOMERS C
JOIN 
    MANAGERS M ON C.MANAGERID = M.ID
JOIN 
    ORDERS O ON C.ID = O.CUSTOMERID
WHERE 
    O.DATE >= '2023-01-01' 
    AND O.AMOUNT >= 1000
GROUP BY 
    C.ID, C.NAME, M.NAME;
